version: '3'
services:

  web:
    # image: "zsnmwy/tieba-cloud-sign"
    build: . 
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWD: janejane123456
      DB_NAME: tiebacloud
      CSRF: "false"
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db


  db:
    image: "hypriot/rpi-mysql"
    environment:
      MYSQL_DATABASE: tiebacloud
      MYSQL_ROOT_PASSWORD: janejane123456
    restart: always
    volumes:
      - /opt/tieba/mysql:/var/lib/mysql
