version: "3"
services:
  ss: 
    image: sslocal:v1                       
    networks:
      - overlay
    volumes:
      - /var/log/:/var/log/
      - ./client/config.json:/app/config.json

                                                                                                          
  h1:
    image: haproxy:v1
    ports:
      - 25502:25502
      - 1115:1115  
    volumes:                
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/curl_get.sh:/app/curl_get.sh
    depends_on:
      - ss
    networks:
      - overlay             
  
networks: 
  overlay: