version: '3'
services:

  web:
    #  build: .
    image: webhippie/php-caddy
    ports:
      - "18880:8080"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./www:/srv/www


  db:
    image: "mysql:5.6.45"
    environment:
      MYSQL_DATABASE: video
      MYSQL_ROOT_PASSWORD: 123

    volumes:
      - ./mysql:/var/lib/mysql
