version: '3'
services:

  web:
    # image: "zsnmwy/tieba-cloud-sign"
    build: .
    ports:
      - "18880:8080"
    links:
      - db
    depends_on:
      - db


  db:
    image: "mysql:5.6.45"
    environment:
      MYSQL_DATABASE: video
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql:/var/lib/mysql
