version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /home/wukt/files/wordpress_file/:/var/www/html
     ports:
       - "25503:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: 123

   db:
     image: mysql:5.7
     volumes:
       - /home/files/wordpress_db/:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: 123
