version: "3"
services:
  ss: 
    image: ss:v1                       
    restart: always                
    networks:
      - overlay
    volumes:
      - /var/log/:/var/log/

  h1:
    image: haproxy
    ports:
      - 24000-24050:24000-24050
      - 1115:1115           
    volumes:                
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - overlay             
  
networks: 
  overlay: