version: "3"
services:
  web:
    image: web_app
    build: .
    restart: always
    ports:
     - "5004:5004"
    volumes:
      - ./logs/docker_log:/api/logs
    networks:
      - overlay
    privileged: true
    deploy:
      mode: replicated
      replicas: 3

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


networks:
  overlay:

# docker build -t web_app  .
# docker stack deploy -c docker-compose.yml web


