version: '3'

services:
  mongodb:
    image: mvertes/alpine-mongo:4.0.1-0
    volumes:
      - mongo_data_yapi:/data/db
    privileged: true
    networks:
      - yapi

  yapi:
    build: .
    ports:
      - 30000:3000
    volumes:
      - ./config.json:/config.json
    depends_on:
      - mongodb
    privileged: true
    networks:
      - yapi

volumes:
  mongo_data_yapi:

networks:
  yapi:
